#! /bin/sh
### BEGIN INIT INFO
# Provides: autostart-alpdeskservice
# Required-Start: $srart
# Required-Stop: $shutdown
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starting Alpdesk-Service
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "starting Alpdesk-Service"
        sh /home/pi/alpdesk/startAlpdeskAutomationservice.sh >> "/home/pi/alpdesk/AlpdeskService.log" 2>&1 &
        ;;
    stop)
        echo "nothing to do"
        ;;
    *)
        echo "Use: /etc/init.d/autostart-alpdeskservice {start|stop}"
        exit 1
        ;;
esac
 
exit 0
