#! /bin/sh
### BEGIN INIT INFO
# Provides: autostart-xhomeautomation
# Required-Start: $srart
# Required-Stop: $shutdown
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starting XHomeautomation
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "starting XHomeautomation"
        sh /home/pi/xhomeautomation/startXHomeautomation.sh >> "/home/pi/xhomeautomation/XHomeautomationLog.log" 2>&1 &
        ;;
    stop)
        echo "nothing to do"
        ;;
    *)
        echo "Use: /etc/init.d/autostart-xhomeautomation {start|stop}"
        exit 1
        ;;
esac
 
exit 0
